<?php

namespace PagosBundle\Repository;

use Doctrine\ORM\EntityRepository;
use PagosBundle\Entity\Company;
use PagosBundle\Entity\Payment;
use PagosBundle\Entity\PaymentMethod;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
	public function findPaymentByCompanyRangeDate(Company $company,$payment_date_from,$payment_date_until)
	{
		$conn = $this->getEntityManager()
		->getConnection();
		
		$sql = "SELECT pay.id FROM payment pay
				JOIN company comp ON comp.id = pay.company_id				
            	WHERE 
				pay.company_id = :company
				AND pay.payment_date between '$payment_date_from' and '$payment_date_until';";
		
		$result = $conn->prepare($sql);
		$result->execute(array('company' => $company->getId()));
		return  $result->fetchAll();
	}
	
	public function findPaymentByRangeDate($payment_date_from,$payment_date_until)
	{
		$conn = $this->getEntityManager()
		->getConnection();
	
		$sql = "SELECT id FROM payment 
		WHERE payment_date between '$payment_date_from' and '$payment_date_until'";
	
		$result = $conn->prepare($sql);
		$result->execute();
		return  $result->fetchAll();
	}
	
}
