_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error
    
pagos_payment:
    resource: "@PagosBundle/Controller/"
    type:     annotation    
    
logout:
    path: /logout
    

    