# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
               users:
                    yoe:
                        password: yoe2020
                        roles: 'ROLE_USER'
                    admin:
                        password: admin2020
                        roles: 'ROLE_ADMIN'

    firewalls:    
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate
            logout_on_user_change: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: app.login
                check_path: app.login
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string
            logout: ~
      
            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext        
        
    access_control:    
         - { path: '^/login/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: '^/', roles: [ROLE_ADMIN,ROLE_USER] }
         - { path: '^/payment', roles: [ROLE_ADMIN,ROLE_USER] }