<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJqyqvul\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJqyqvul/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJqyqvul.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJqyqvul\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJqyqvul\appDevDebugProjectContainer([
    'container.build_hash' => 'Jqyqvul',
    'container.build_id' => '88e3bbab',
    'container.build_time' => 1596166843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJqyqvul');
